/* =============================================================
   TERMS OF USE — Sara Siblini | Primerica Life Insurance Company of Canada
   Ontario law. FSRA. Content per Prompt 5 spec.
   Visual layout preserved — text content only replaced.
   ============================================================= */
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import PageHeader from "@/components/PageHeader";

export default function Terms() {
  return (
    <div className="min-h-screen flex flex-col">
      <Navbar />
      <div className="pt-16 lg:pt-20">
        <PageHeader title="Terms of Use — Sara Siblini Insurance" breadcrumbs={[{ label: "Terms of Use" }]} />
        <section className="py-16 bg-white">
          <div className="container mx-auto px-4 lg:px-8 max-w-3xl">
            <div className="prose prose-slate max-w-none text-sm leading-relaxed text-gray-700 space-y-6">
              <p className="text-gray-500 text-xs">Last updated: [SARA TO FILL IN — date when site goes live]</p>

              <h2 className="font-['Playfair_Display'] text-xl font-bold text-[#1a365d] mt-8">Acceptance of Terms</h2>
              <p>By using this website, you agree to these Terms of Use. If you do not agree, please do not use this site.</p>

              <h2 className="font-['Playfair_Display'] text-xl font-bold text-[#1a365d] mt-8">About This Website</h2>
              <p>This website is operated by Sara Siblini, a Licensed Life Insurance Representative with Primerica Life Insurance Company of Canada (FSRA Lic. #NUV56), serving residents of Ontario, Canada. This site provides general information about life insurance and allows prospective clients to request a quote or book a consultation.</p>

              <h2 className="font-['Playfair_Display'] text-xl font-bold text-[#1a365d] mt-8">Not a Binding Quote</h2>
              <p>Any quote estimate generated by the calculator on this site is for illustrative purposes only. It does not constitute an offer of insurance coverage or a binding commitment by Primerica Life Insurance Company of Canada. Actual coverage and premiums are subject to underwriting approval and may differ from any estimate provided on this site.</p>

              <h2 className="font-['Playfair_Display'] text-xl font-bold text-[#1a365d] mt-8">Licensed in Ontario Only</h2>
              <p>Sara Siblini is licensed to sell life insurance products in Ontario, Canada only. This website is intended for Ontario residents. Information on this site may not be applicable in other provinces or countries.</p>

              <h2 className="font-['Playfair_Display'] text-xl font-bold text-[#1a365d] mt-8">No Financial or Legal Advice</h2>
              <p>Content on this website is for informational purposes only and does not constitute financial, legal, tax, or estate planning advice. Please consult a qualified professional for advice specific to your situation.</p>

              <h2 className="font-['Playfair_Display'] text-xl font-bold text-[#1a365d] mt-8">Third-Party Links</h2>
              <p>This site may link to third-party websites (e.g., Calendly for booking). Sara Siblini is not responsible for the content or privacy practices of those sites.</p>

              <h2 className="font-['Playfair_Display'] text-xl font-bold text-[#1a365d] mt-8">Limitation of Liability</h2>
              <p>Sara Siblini and Primerica Life Insurance Company of Canada are not liable for any damages arising from your use of this website or reliance on information presented here.</p>

              <h2 className="font-['Playfair_Display'] text-xl font-bold text-[#1a365d] mt-8">Governing Law</h2>
              <p>These terms are governed by the laws of Ontario and the federal laws of Canada applicable therein.</p>

              <h2 className="font-['Playfair_Display'] text-xl font-bold text-[#1a365d] mt-8">Contact</h2>
              <p>
                Sara Siblini<br />
                Licensed Life Insurance Representative<br />
                Primerica Life Insurance Company of Canada<br />
                FSRA Lic. #NUV56 | Ontario, Canada<br />
                Email: [SARA TO FILL IN — business email address]
              </p>
            </div>
          </div>
        </section>
      </div>
      <Footer />
    </div>
  );
}
